# Generated by Django 5.0.6 on 2024-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="852ee4c99cb4d6c5d4eaba798cfd537350901ed5",
                max_length=40,
                null=True,
            ),
        ),
    ]
