# Generated by Django 5.0.6 on 2024-07-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="a83ba281284ff0596b7bf06ab201f080d0599ecd95cc5a287e5f4e8ef5d3ed6690fa3409e88161e5",
                max_length=40,
                null=True,
            ),
        ),
    ]
