# Generated by Django 5.0.6 on 2024-06-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=True, verbose_name="Суперпользователь"),
        ),
    ]
