# Generated by Django 5.0.6 on 2024-07-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_looking',
            field=models.BooleanField(default=False, verbose_name='Смотрит'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='platform_name',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Наименование площадки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='3d37ae3b9b22553e7057699db068a8e3da9d42ddc0891b49dec2c3474e322f4d12bd9ad979c9f0d2', max_length=40, null=True),
        ),
    ]
