# Generated by Django 5.0.6 on 2024-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_verify_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="cb569c87d1913552a21a1056fb2fb98d3efa69e2",
                max_length=40,
                null=True,
            ),
        ),
    ]
