# Generated by Django 5.0.6 on 2024-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_verify_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="8e4144440c316552cd71e38332a8f3dc3cd910e8",
                max_length=40,
                null=True,
            ),
        ),
    ]
