# Generated by Django 5.0.6 on 2024-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="09519c6e0aa4e2b1433350021c9b529010a067d626eccf1587b7963e06e11452b1eb8eb40f4a7081",
                max_length=40,
                null=True,
            ),
        ),
    ]
