# Generated by Django 5.0.6 on 2024-09-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='ebacfce64fb2616affa38b064743fb8e6c29020aff2867f26b09004a9ca577a5d2dea495a4ad6625', max_length=40, null=True),
        ),
    ]
