# Generated by Django 5.0.6 on 2024-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_verify_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="bad62c04297d8a21284f3e27d9cfee775d622474962b8b5a4e60f7769a12f5673c3f4ff3135e23bb",
                max_length=40,
                null=True,
            ),
        ),
    ]
