# Generated by Django 5.0.6 on 2024-09-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_verify_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="153f735b4385a5ecb372328780fa8db08c5a8e354600b6f9c4039a79e607bd0ae42f7c78799b14ab",
                max_length=40,
                null=True,
            ),
        ),
    ]
