# Generated by Django 5.0.6 on 2024-10-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_verify_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verify_token",
            field=models.CharField(
                blank=True,
                default="af5f82a53cda7c4d8e6fd745e01e139f500fd52a",
                max_length=40,
                null=True,
            ),
        ),
    ]
