# Generated by Django 5.0.6 on 2024-10-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='48ef25445ae137570d683ebdde5e5eddadccb4de168597349c25751c9c9bc7c96874d496348f478d', max_length=40, null=True),
        ),
    ]
