# Generated by Django 5.0.6 on 2024-10-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='3b58efcd482a07af85ce1badcaaea9944e9305b66350264ed5daf599d24e68a442475ee57c8e6444', max_length=40, null=True),
        ),
    ]
