# Generated by Django 5.0.6 on 2024-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='d363f389957e8c1a5b740dcb8b5d56bd07d8e429feae75dad8cca6226d06e00333f534af0e5af849', max_length=40, null=True),
        ),
    ]
