# Generated by Django 5.0.6 on 2024-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='17260cf3d3c643b8d1df10d7fc9d5a98b069f627aa64f4f65249445651ded37feda6a3f5bdd7de3d', max_length=40, null=True),
        ),
    ]
