# Generated by Django 5.0.6 on 2024-10-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='233f1c9ee6ffa0ba68438f9b540c97170603f6e1880632129f6c7c7a71ad3fc12cb02f15a31e7166', max_length=40, null=True),
        ),
    ]
