# Generated by Django 5.0.6 on 2024-10-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='ba77858d74c3466be0a770b65d3c385a53d0dde729b6769826ccea62a8a49c696cc8c94903241865', max_length=40, null=True),
        ),
    ]
