# Generated by Django 5.0.6 on 2024-10-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='5a06ba1ede2f99ae2c44dab8cf43b0cf1a403d0a5566a7bc5acda5e7d72e8d034bba9d545cf9e7a8', max_length=40, null=True),
        ),
    ]
