# Generated by Django 5.0.6 on 2024-10-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='ebc60a11fcde0538c2ed86d1c18fe7f24ec1f2b186afe22d4d9e52d6949e1aeb98bbd3ae6da08009', max_length=40, null=True),
        ),
    ]
