# Generated by Django 5.0.6 on 2024-10-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customuser_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verify_token',
            field=models.CharField(blank=True, default='0f6275d2fb2409e7b9929f5a0c90aeca675d719b5219fc67d02018bec40e047f90f54f0e7e89b7e5', max_length=40, null=True),
        ),
    ]
