# Generated by Django 5.1.2 on 2024-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CopyrightInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("possessor", models.TextField(verbose_name="Правообладатель")),
                (
                    "possessor_email",
                    models.EmailField(
                        max_length=254, verbose_name="Почта правообладателя"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=1000, verbose_name="Контакт для связи (телефон)"
                    ),
                ),
                (
                    "contact_email",
                    models.CharField(
                        max_length=1000, verbose_name="Контакт для связи (почта)"
                    ),
                ),
            ],
            options={
                "verbose_name": " Информация о правообладателе",
            },
        ),
        migrations.CreateModel(
            name="InviteSpecialists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=225, verbose_name="Электронный адрес"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "who_is",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Кем является",
                    ),
                ),
                ("accept", models.BooleanField(default=False, verbose_name="Принято")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "ordering": ["created_date"],
            },
        ),
        migrations.CreateModel(
            name="MovieApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Название фильма"),
                ),
                (
                    "year",
                    models.DecimalField(
                        decimal_places=0, max_digits=4, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "rolled_certificate",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Прокатное удостоверение",
                    ),
                ),
                ("timing", models.CharField(max_length=20, verbose_name="Хронометраж")),
                (
                    "actors",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="В ролях"
                    ),
                ),
                ("logline", models.TextField(verbose_name="Логлайн")),
                ("debut", models.BooleanField(default=False, verbose_name="Дебютный")),
                (
                    "music",
                    models.BooleanField(
                        default=False, verbose_name="Оригинальная музыка"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2000,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "other_country",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2000,
                        null=True,
                        verbose_name="Другая страна",
                    ),
                ),
                (
                    "other_region",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2000,
                        null=True,
                        verbose_name="Другой регион",
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2000,
                        null=True,
                        verbose_name="Населенный пункт",
                    ),
                ),
                (
                    "other_shooting_group",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Остальные члены съемочной команды",
                    ),
                ),
                (
                    "agreement_to_placement",
                    models.BooleanField(
                        default=False,
                        null=True,
                        verbose_name="согласие на размещение на сайте",
                    ),
                ),
                (
                    "agreement_to_vote",
                    models.BooleanField(
                        default=False, null=True, verbose_name="согласие на голосование"
                    ),
                ),
                (
                    "agreement_to_no_commerce_show",
                    models.BooleanField(
                        default=False,
                        null=True,
                        verbose_name="согласие на некоммерческие показы",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal",
                    models.BooleanField(default=False, verbose_name="Юридическое лицо"),
                ),
                (
                    "individual",
                    models.BooleanField(default=False, verbose_name="Физическое лицо"),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2000,
                        null=True,
                        verbose_name="Название организации",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "movie_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Адрес регистрации",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="ИНН"
                    ),
                ),
                (
                    "payroll",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Расчётный счёт",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Название банка",
                    ),
                ),
                (
                    "bik",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="БИК"
                    ),
                ),
                (
                    "correction",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Коррекционный счет",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Номер паспорта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Договор",
                "verbose_name_plural": "Договора",
            },
        ),
        migrations.CreateModel(
            name="MoviePortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("festivals", models.TextField(verbose_name="Участие в фестивалях")),
                ("internet", models.TextField(verbose_name="Охват в интернете")),
                ("smi", models.TextField(verbose_name="Публикации в СМИ")),
                (
                    "materials",
                    models.TextField(verbose_name="Ссылка для скачивания материалов"),
                ),
            ],
            options={
                "verbose_name": " Портфолио",
                "verbose_name_plural": " Портфолио",
            },
        ),
        migrations.CreateModel(
            name="SpecialistApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "other_speciality",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Другая специальность",
                    ),
                ),
                (
                    "portfolio",
                    models.URLField(
                        default=None, null=True, verbose_name="Ссылка на портфолио"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default=None,
                        max_length=1000,
                        null=True,
                        verbose_name="Населенный пункт",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default=None, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default=None,
                        max_length=225,
                        null=True,
                        verbose_name="Электронный адрес",
                    ),
                ),
                (
                    "social_link",
                    models.TextField(
                        default=None,
                        null=True,
                        verbose_name="Ссылка на социальные сети",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        default=None, null=True, verbose_name="Дополнительно"
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Биография"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалист",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Статус")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
    ]
