# Generated by Django 5.1.2 on 2024-10-31 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("movies", "0001_initial"),
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitespecialists",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="age_limit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.agelimit",
                verbose_name="Возрастное ограничение",
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="copyright_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.copyrightinformation",
                verbose_name="Информация о правообладателе",
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="genre",
            field=models.ManyToManyField(
                blank=True, default=None, to="movies.genre", verbose_name="Жанр"
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="movies.kind",
                verbose_name="Вид",
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="regions",
            field=models.ManyToManyField(
                blank=True, default=None, to="regions.region", verbose_name="Регионы"
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="shooting_group",
            field=models.ManyToManyField(to="movies.mainshootinggroup"),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="contract",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.moviecontract",
                verbose_name="Договор",
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="portfolio",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.movieportfolio",
                verbose_name="Ссылка на портфолио",
            ),
        ),
        migrations.AddField(
            model_name="specialistapp",
            name="region",
            field=models.ManyToManyField(to="regions.region", verbose_name="Регион"),
        ),
        migrations.AddField(
            model_name="specialistapp",
            name="speciality",
            field=models.ManyToManyField(
                related_name="app_specialities", to="regions.speciality"
            ),
        ),
        migrations.AddField(
            model_name="specialistapp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="specialistapp",
            name="status",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="movieapp",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.status",
                verbose_name="Статус",
            ),
        ),
    ]
