# Generated by Django 5.0.6 on 2024-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdirector',
            name='biography',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='appproducer',
            name='biography',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='appscenarist',
            name='biography',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Биография'),
        ),
    ]
