# Generated by Django 5.0.6 on 2024-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_copyrightinformation_moviecontract_movieportfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieapp',
            name='agreement_to_no_commerce_show',
            field=models.BooleanField(default=False, null=True, verbose_name='согласие на некоммерческие показы'),
        ),
        migrations.AlterField(
            model_name='movieapp',
            name='agreement_to_placement',
            field=models.BooleanField(default=False, null=True, verbose_name='согласие на размещение на сайте'),
        ),
        migrations.AlterField(
            model_name='movieapp',
            name='agreement_to_vote',
            field=models.BooleanField(default=False, null=True, verbose_name='согласие на голосование'),
        ),
    ]
