# Generated by Django 5.0.6 on 2024-09-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_movieapp_agreement_to_no_commerce_show_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieapp',
            name='trailer',
        ),
    ]
