# Generated by Django 5.0.6 on 2024-09-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_movieapp_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieapp',
            name='is_active',
        ),
    ]
