# Generated by Django 5.0.6 on 2024-09-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_movieapp_is_active'),
        ('regions', '0004_remove_specialist_status_remove_specialist_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistapp',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='specialistapp',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='specialistapp',
            name='region',
        ),
        migrations.AddField(
            model_name='specialistapp',
            name='region',
            field=models.ManyToManyField(to='regions.region', verbose_name='Регион'),
        ),
    ]
