# Generated by Django 5.0.6 on 2024-09-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_remove_specialistapp_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieapp',
            name='contract',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='applications.moviecontract', verbose_name='Договор'),
            preserve_default=False,
        ),
    ]
