# Generated by Django 5.0.6 on 2024-09-17 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_movieapp_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecontract',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviecontract',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
