# Generated by Django 5.0.6 on 2024-09-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_moviecontract_birthday_moviecontract_passport_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieapp',
            name='slug',
        ),
    ]
