# Generated by Django 5.0.6 on 2024-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_movieapp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistapp',
            name='portfolio',
            field=models.URLField(default=None, null=True, verbose_name='Ссылка на портфолио'),
        ),
    ]
