# Generated by Django 5.0.6 on 2024-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_specialistapp_city_and_more'),
        ('regions', '0004_remove_specialist_status_remove_specialist_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistapp',
            name='region',
            field=models.ManyToManyField(to='regions.region', verbose_name='Регион'),
        ),
    ]
