# Generated by Django 5.0.6 on 2024-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_specialistapp_region'),
        ('regions', '0004_remove_specialist_status_remove_specialist_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialistapp',
            name='speciality',
            field=models.ManyToManyField(related_name='app_specialities', to='regions.speciality'),
        ),
    ]
