# Generated by Django 5.0.6 on 2024-10-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0018_alter_movieapp_shooting_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="copyrightinformation",
            options={"verbose_name": " Информация о правообладателе"},
        ),
        migrations.AlterModelOptions(
            name="moviecontract",
            options={"verbose_name": "Договор", "verbose_name_plural": "Договора"},
        ),
        migrations.AlterModelOptions(
            name="movieportfolio",
            options={"verbose_name": " Портфолио", "verbose_name_plural": " Портфолио"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Статус", "verbose_name_plural": "Статусы"},
        ),
    ]
