# Generated by Django 5.0.6 on 2024-10-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_alter_copyrightinformation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieapp",
            name="contract",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.moviecontract",
                verbose_name="Договор",
            ),
        ),
    ]
