# Generated by Django 5.0.6 on 2024-09-01 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Голосование"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("start", models.DateField(verbose_name="Начало")),
                ("end", models.DateField(verbose_name="Конец")),
                (
                    "movies",
                    models.ManyToManyField(related_name="movies", to="movies.movie"),
                ),
            ],
            options={
                "verbose_name": "Голосование",
                "verbose_name_plural": "Голосования",
            },
        ),
        migrations.CreateModel(
            name="VoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="voting.voting"
                    ),
                ),
            ],
        ),
    ]
