# Generated by Django 5.0.6 on 2024-10-06 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0036_alter_movie_timing"),
        ("voting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voting",
            options={
                "verbose_name": "Голосование",
                "verbose_name_plural": "Голосование",
            },
        ),
        migrations.RemoveField(
            model_name="voting",
            name="end",
        ),
        migrations.RemoveField(
            model_name="voting",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="voting",
            name="start",
        ),
        migrations.AddField(
            model_name="voting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="voting",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата окончания голосования",
            ),
        ),
        migrations.AddField(
            model_name="voting",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата начала голосования",
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="movies",
            field=models.ManyToManyField(
                related_name="voting_movies", to="movies.movie", verbose_name="Фильмы"
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="name",
            field=models.CharField(max_length=2000, verbose_name="Наименование"),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Голоса",
                "verbose_name_plural": "Голос",
                "unique_together": {("movie", "user")},
            },
        ),
        migrations.DeleteModel(
            name="VoteItem",
        ),
    ]
