# Generated by Django 5.0.6 on 2024-10-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0002_alter_voting_options_remove_voting_end_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vote",
            options={"verbose_name": "Голос", "verbose_name_plural": "Голоса"},
        ),
    ]
