# Generated by Django 5.0.6 on 2024-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_alter_vote_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="voting",
            name="slug",
            field=models.SlugField(default="test"),
            preserve_default=False,
        ),
    ]
