# Generated by Django 5.0.6 on 2024-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0004_voting_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
