# Generated by Django 5.1.2 on 2024-10-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtisticalDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Художник постановщик",
                "verbose_name_plural": "Художник постановщик",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Населенный пункт",
                "verbose_name_plural": "Населенный пункт",
            },
        ),
        migrations.CreateModel(
            name="Compositor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Композитор",
                "verbose_name_plural": "Композиторы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="CostumerDesigner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Художник по костюмам",
                "verbose_name_plural": "Художник по костюмам",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                ("biography", models.TextField(verbose_name="Биография")),
                ("slug", models.SlugField(blank=True)),
            ],
            options={
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режиссеры",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="LocationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="793x531",
                        upload_to="regions/locations/locations_albums/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Фотография локации",
                "verbose_name_plural": "Фотографии локаций",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Оператор",
                "verbose_name_plural": "Операторы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                ("biography", models.TextField(verbose_name="Биография")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Продюссер",
                "verbose_name_plural": "Продюссеры",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("other", models.BooleanField(default=False, verbose_name="Другой")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Регионы",
                "verbose_name_plural": "Регион",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Scenarist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                ("biography", models.TextField(verbose_name="Биография")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Сценарист",
                "verbose_name_plural": "Сценаристы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Специальность",
                "verbose_name_plural": "Специальность",
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                ("logo", models.ImageField(upload_to="regions/productions/")),
                ("services_type", models.TextField(verbose_name="Тип услуг")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "social_net",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Ссылка на соцсеть",
                    ),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Сайт")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("slug", models.SlugField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Производство",
                "verbose_name_plural": "Производства",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                ("slug", models.SlugField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="regions.region"
                    ),
                ),
            ],
            options={
                "verbose_name": "Населённый пункт",
                "verbose_name_plural": "Населённый пункт",
            },
        ),
        migrations.CreateModel(
            name="FilmmakersChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "link_to_chat",
                    models.URLField(blank=True, verbose_name="Ссылка на чат"),
                ),
                ("slug", models.SlugField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат кинематографистов",
                "verbose_name_plural": "Чаты кинематографистов",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="1844x2176",
                        upload_to="regions/events/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(blank=True, verbose_name="Краткая информация"),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Сайт"
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="RegionalInternetResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                ("link", models.URLField(verbose_name="Ссылка на ресурс")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("slug", models.SlugField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Региональный интернет ресурс",
                "verbose_name_plural": "Региональные интернет ресурсы ",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="RegionalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="regions/regional_profile/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(blank=True, verbose_name="Краткая информация"),
                ),
                ("citation", models.TextField(blank=True, verbose_name="Цитата")),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Автор цитаты"
                    ),
                ),
                (
                    "link_to_video",
                    models.URLField(blank=True, verbose_name="Ссылка на видео"),
                ),
                (
                    "link_to_presentation",
                    models.URLField(blank=True, verbose_name="Ссылка на презентацию"),
                ),
                ("slug", models.SlugField()),
                (
                    "author_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="regions.city",
                        verbose_name="Локация автора",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Портрет региона",
                "verbose_name_plural": "Портреты региона",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="RegionLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "main_photo",
                    models.ImageField(
                        blank=True, help_text="397x379", upload_to="regions/locations/"
                    ),
                ),
                ("descriptions", models.TextField(blank=True, verbose_name="Описание")),
                ("circumstances", models.TextField(blank=True, verbose_name="Условия")),
                (
                    "subclass",
                    models.TextField(blank=True, verbose_name="Дополнительно"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=5000, verbose_name="Адрес"),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Координаты"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "social_net",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Ссылка на соцсеть",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Сайт"
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "photo",
                    models.ManyToManyField(
                        blank=True,
                        related_name="photos",
                        to="regions.locationphoto",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "social_net",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Ссылка на соцсеть",
                    ),
                ),
                ("site", models.URLField(blank=True, null=True, verbose_name="Сайт")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="397x248", upload_to="regions/screening_points/"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("slug", models.SlugField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Точка кинопоказа",
                "verbose_name_plural": "Точки кинопоказа",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="469x351",
                        upload_to="regions/specialists/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Фамилия"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(max_length=225, verbose_name="Электронный адрес"),
                ),
                (
                    "portfolio_link",
                    models.URLField(blank=True, verbose_name="Ссылка на портфолио"),
                ),
                (
                    "social_link",
                    models.URLField(
                        blank=True, verbose_name="Ссылка на социальные сети"
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(blank=True, verbose_name="Дополнительно"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="regions.city",
                        verbose_name="Населенный пункт",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
                (
                    "speciality",
                    models.ManyToManyField(
                        related_name="specialities", to="regions.speciality"
                    ),
                ),
            ],
            options={
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
    ]
