# Generated by Django 5.0.6 on 2024-09-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенный пункт',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальность',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('photo', models.FileField(upload_to='specialists/', verbose_name='Фотография')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=225, verbose_name='Электронный адрес')),
                ('portfolio_link', models.URLField(verbose_name='Ссылка на портфолио')),
                ('social_link', models.URLField(verbose_name='Ссылка на социальные сети')),
                ('descriptions', models.TextField(verbose_name='Дополнительно')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.city', verbose_name='Населенный пункт')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.region', verbose_name='Регион')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.status', verbose_name='Статус')),
                ('speciality', models.ManyToManyField(related_name='specialities', to='regions.speciality')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалист',
            },
        ),
    ]
