# Generated by Django 5.1.2 on 2024-12-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={
                "ordering": ["last_name"],
                "verbose_name": "Специалист",
                "verbose_name_plural": "Специалисты",
            },
        ),
        migrations.AlterField(
            model_name="regionalprofile",
            name="link_to_video",
            field=models.URLField(
                blank=True, max_length=2000, verbose_name="Ссылка на видео"
            ),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="city",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="regions.city",
                verbose_name="Населенный пункт",
            ),
        ),
    ]
