# Generated by Django 5.1.2 on 2024-12-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0002_alter_specialist_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalprofile",
            name="link_to_video",
            field=models.CharField(
                blank=True, max_length=2000, verbose_name="Ссылка на видео"
            ),
        ),
    ]
