# Generated by Django 5.1.2 on 2024-12-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0003_alter_regionalprofile_link_to_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalprofile",
            name="link_to_presentation",
            field=models.FileField(
                blank=True,
                upload_to="presentations/",
                verbose_name="Ссылка на презентацию",
            ),
        ),
    ]
