# Generated by Django 5.0.6 on 2024-09-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_location_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='surname',
        ),
    ]
