# Generated by Django 5.0.6 on 2024-10-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_remove_specialist_status_remove_specialist_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Композитор',
                'verbose_name_plural': 'Композиторы',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Режиссер фильма',
                'verbose_name_plural': 'Режиссеры фильмов',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Продюссер',
                'verbose_name_plural': 'Продюссеры',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Scenarist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Сценарист',
                'verbose_name_plural': 'Сценаристы',
                'ordering': ['last_name'],
            },
        ),
    ]
