# Generated by Django 5.1.2 on 2024-12-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0004_alter_regionalprofile_link_to_presentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regionalprofile",
            name="link_to_presentation",
            field=models.FileField(
                blank=True, upload_to="presentations/", verbose_name="Презентация"
            ),
        ),
        migrations.AlterField(
            model_name="regionlocation",
            name="main_photo",
            field=models.ImageField(
                help_text="397x379", upload_to="regions/locations/"
            ),
        ),
    ]
