# Generated by Django 5.0.6 on 2024-10-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_compositor_director_operator_producer_scenarist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['last_name'], 'verbose_name': 'Режиссер', 'verbose_name_plural': 'Режиссеры'},
        ),
    ]
