# Generated by Django 5.0.6 on 2024-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0006_alter_director_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtisticalDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Художник постановщик",
                "verbose_name_plural": "Художник постановщик",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="CostumerDesigner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Художник по костюмам",
                "verbose_name_plural": "Художник по костюмам",
                "ordering": ["last_name"],
            },
        ),
    ]
