# Generated by Django 5.0.6 on 2024-10-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0008_screeningpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screeningpoint",
            name="address",
            field=models.CharField(
                blank=True, max_length=2000, null=True, verbose_name="Адрес"
            ),
        ),
    ]
