# Generated by Django 5.0.6 on 2024-10-22 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0009_alter_screeningpoint_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="regions/locations/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Фотография локации",
                "verbose_name_plural": "Фотографии локаций",
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="screeningpoint",
            name="created_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screeningpoint",
            name="edit_date",
            field=models.DateField(auto_now=True, verbose_name="Дата изменения"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="photo",
            field=models.ImageField(
                upload_to="regions/specialists/", verbose_name="Фотография"
            ),
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="regions/events/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(blank=True, verbose_name="Краткая информация"),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Сайт"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="FilmmakersChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "link_to_chat",
                    models.URLField(blank=True, verbose_name="Ссылка на чат"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат кинематографистов",
                "verbose_name_plural": "Чаты кинематографистов",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                ("logo", models.ImageField(upload_to="regions/productions/")),
                ("services_type", models.TextField(verbose_name="Тип услуг")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "social_net",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Ссылка на соцсеть",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Сайт"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Производство",
                "verbose_name_plural": "Производства",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="RegionalInternetResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                ("link", models.URLField(verbose_name="Ссылка на ресурс")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Региональный интернет ресурс",
                "verbose_name_plural": "Региональные интернет ресурсы ",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="RegionalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="regions/regional_profile/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(blank=True, verbose_name="Краткая информация"),
                ),
                (
                    "link_to_video",
                    models.URLField(blank=True, verbose_name="Ссылка на видео"),
                ),
                (
                    "link_to_presentation",
                    models.URLField(blank=True, verbose_name="Ссылка на презентацию"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Портрет региона",
                "verbose_name_plural": "Портреты региона",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="RegionLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("name", models.CharField(max_length=2000, verbose_name="Название")),
                (
                    "descriptions",
                    models.TextField(blank=True, verbose_name="Краткая информация"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=5000, verbose_name="Адрес"),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Координаты"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "social_net",
                    models.CharField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Ссылка на соцсеть",
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True, max_length=2000, null=True, verbose_name="Сайт"
                    ),
                ),
                (
                    "photo",
                    models.ManyToManyField(
                        blank=True,
                        related_name="photos",
                        to="regions.locationphoto",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
                "ordering": ["-created_date"],
            },
        ),
    ]
