# Generated by Django 5.0.6 on 2024-10-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0011_events_slug_filmmakerschat_slug_production_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screeningpoint",
            name="image",
            field=models.ImageField(
                help_text="397x248", upload_to="regions/screening_points/"
            ),
        ),
        migrations.AlterField(
            model_name="screeningpoint",
            name="site",
            field=models.URLField(blank=True, null=True, verbose_name="Сайт"),
        ),
    ]
