# Generated by Django 5.0.6 on 2024-09-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, verbose_name="Возрастное ограничение"
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Возрастное ограничение",
                "verbose_name_plural": "Возрастные ограничения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Almanach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "main",
                    models.BooleanField(
                        default=False, verbose_name="Главный на странице"
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Альмонарх")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Альмонарх фильма",
                "verbose_name_plural": "Альмонархи фильмов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Категории",
                "verbose_name_plural": "Категория",
            },
        ),
        migrations.CreateModel(
            name="Compositor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Композитор",
                "verbose_name_plural": "Композиторы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Режиссер фильма",
                "verbose_name_plural": "Режиссеры фильмов",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Жанры",
                "verbose_name_plural": "Жанр",
            },
        ),
        migrations.CreateModel(
            name="Kind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Типы",
                "verbose_name_plural": "Тип",
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Оператор",
                "verbose_name_plural": "Операторы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Продюссер",
                "verbose_name_plural": "Продюссеры",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="RatingStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.SmallIntegerField(default=0, verbose_name="Значение")),
            ],
            options={
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
                "ordering": ["-value"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Регионы",
                "verbose_name_plural": "Регион",
            },
        ),
        migrations.CreateModel(
            name="Scenarist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Сценарист",
                "verbose_name_plural": "Сценаристы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Статус")),
                (
                    "show",
                    models.BooleanField(
                        default=False, verbose_name="Не показвать фильм"
                    ),
                ),
                (
                    "archive",
                    models.BooleanField(
                        default=False, verbose_name="Переносить в архив"
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Статус фильма",
                "verbose_name_plural": "Статусы фильмов",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Название фильма"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="movie_image/", verbose_name="Картинка"
                    ),
                ),
                (
                    "year",
                    models.DecimalField(
                        decimal_places=0, max_digits=4, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "rolled_certificate",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Прокатное удостоверение",
                    ),
                ),
                ("trailer", models.URLField()),
                ("timing", models.CharField(max_length=20, verbose_name="Хронометраж")),
                ("actors", models.TextField(verbose_name="В ролях")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "voting",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Ссылка на голосование",
                    ),
                ),
                (
                    "close",
                    models.BooleanField(default=False, verbose_name="Закрытый фильм"),
                ),
                ("slug", models.SlugField()),
                (
                    "age_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.agelimit",
                        verbose_name="Возрастное ограничение",
                    ),
                ),
                (
                    "almanach",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        to="movies.almanach",
                        verbose_name="Альманах",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "compositor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.compositor",
                        verbose_name="Композитор",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.director",
                        verbose_name="Режиссер",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        blank=True, default=None, to="movies.genre", verbose_name="Жанр"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.operator",
                        verbose_name="Оператор",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.producer",
                        verbose_name="Продюссер",
                    ),
                ),
                (
                    "scenarist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.scenarist",
                        verbose_name="Сценарист",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.status",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
                "ordering": ["created_date"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=15, unique=True, verbose_name="IP")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="Фильм",
                    ),
                ),
                (
                    "star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="movies.ratingstar",
                        verbose_name="Оценка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
                "ordering": ["created_date"],
            },
        ),
    ]
