# Generated by Django 5.1.2 on 2024-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgeLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, verbose_name="Возрастное ограничение"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Описание"
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Возрастное ограничение",
                "verbose_name_plural": "Возрастные ограничения",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Almanac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "on_slide",
                    models.BooleanField(default=False, verbose_name="На слайде"),
                ),
                (
                    "slide_image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="movies/main/slides",
                        verbose_name="Картинка слайдера",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Короткое название",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="movies/main/slides", verbose_name="Картинка"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "laureate",
                    models.BooleanField(default=False, verbose_name="Лауреат"),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=4,
                        null=True,
                        verbose_name="Год",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Альманах",
                "verbose_name_plural": "Альманахи",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Категории",
                "verbose_name_plural": "Категория",
            },
        ),
        migrations.CreateModel(
            name="CategoryGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Жанр вида",
                "verbose_name_plural": "Жанр вида",
            },
        ),
        migrations.CreateModel(
            name="FavoriteMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата добавления"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["-added_date"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                (
                    "group_1",
                    models.BooleanField(default=False, verbose_name="Группа 1"),
                ),
                (
                    "group_2",
                    models.BooleanField(default=False, verbose_name="Группа 2"),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Жанры",
                "verbose_name_plural": "Жанр",
            },
        ),
        migrations.CreateModel(
            name="Kind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Типы",
                "verbose_name_plural": "Тип",
            },
        ),
        migrations.CreateModel(
            name="MainShootingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Биография"
                    ),
                ),
            ],
            options={
                "verbose_name": "Съемочные группы",
                "verbose_name_plural": "Съемочная группа",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "name",
                    models.CharField(max_length=500, verbose_name="Название фильма"),
                ),
                (
                    "search_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Название для поиска"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="movie_image/", verbose_name="Картинка"
                    ),
                ),
                (
                    "year",
                    models.DecimalField(
                        decimal_places=0, max_digits=4, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "rolled_certificate",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Прокатное удостоверение",
                    ),
                ),
                ("timing", models.CharField(max_length=20, verbose_name="Хронометраж")),
                ("actors", models.TextField(blank=True, verbose_name="В ролях")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "vk_iframe",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Ссылка на iframe - фильм",
                    ),
                ),
                (
                    "close",
                    models.BooleanField(default=False, verbose_name="Закрытый фильм"),
                ),
                ("debut", models.BooleanField(default=False, verbose_name="Дебютный")),
                (
                    "music",
                    models.BooleanField(
                        default=False, verbose_name="Оригинальная музыка"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2000,
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "other_region",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=2000,
                        null=True,
                        verbose_name="Другой регион",
                    ),
                ),
                (
                    "trailer",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Ссылка на iframe - трейлер",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
                "ordering": ["created_date"],
            },
        ),
        migrations.CreateModel(
            name="MovieStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Статус")),
                (
                    "show",
                    models.BooleanField(
                        default=False, verbose_name="Не показвать фильм"
                    ),
                ),
                (
                    "archive",
                    models.BooleanField(
                        default=False, verbose_name="Переносить в архив"
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название плейлиста"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание плейлиста"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Плейлист",
                "verbose_name_plural": "Плейлисты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=15, verbose_name="IP")),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Рейтинг",
                "verbose_name_plural": "Рейтинги",
                "ordering": ["created_date"],
            },
        ),
        migrations.CreateModel(
            name="RatingStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.SmallIntegerField(default=0, verbose_name="Значение")),
            ],
            options={
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="RollerCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Прокатное удостоверение",
                "verbose_name_plural": "Прокатное удостоверение",
            },
        ),
        migrations.CreateModel(
            name="ShootingGroupSpecialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активность"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1000, verbose_name="Наименование специальности"
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Специалист съемочной группы",
                "verbose_name_plural": "Специалист съемочной группы",
            },
        ),
    ]
