# Generated by Django 5.1.2 on 2024-10-31 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritemovie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_movies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="age_limit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.agelimit",
                verbose_name="Возрастное ограничение",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="almanach",
            field=models.ManyToManyField(
                blank=True, default=None, to="movies.almanac", verbose_name="Альманах"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="artistical_director",
            field=models.ManyToManyField(
                blank=True,
                to="regions.artisticaldirector",
                verbose_name="Художник постановщик",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="compositor",
            field=models.ManyToManyField(
                blank=True, to="regions.compositor", verbose_name="Композитор-регион"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="costumer_designer",
            field=models.ManyToManyField(
                blank=True,
                to="regions.costumerdesigner",
                verbose_name="Художник по костюмам",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ManyToManyField(
                blank=True,
                related_name="directors",
                to="regions.director",
                verbose_name="Режиссеры-регион",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(
                blank=True, default=None, to="movies.genre", verbose_name="Жанр"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="kind",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="movies.kind",
                verbose_name="Вид",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="operator",
            field=models.ManyToManyField(
                blank=True, to="regions.operator", verbose_name="Оператор-регион"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="producer",
            field=models.ManyToManyField(
                blank=True,
                related_name="producers",
                to="regions.producer",
                verbose_name="Продюссеры-регион",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="regions",
            field=models.ManyToManyField(
                related_name="movie_regions", to="regions.region"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="scenarist",
            field=models.ManyToManyField(
                blank=True,
                related_name="scenarists",
                to="regions.scenarist",
                verbose_name="Сценарист-регион",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="shooting_group",
            field=models.ManyToManyField(
                blank=True,
                related_name="movies",
                to="movies.mainshootinggroup",
                verbose_name="Съемочная группа",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Добавил",
            ),
        ),
        migrations.AddField(
            model_name="favoritemovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="movies.movie",
                verbose_name="Фильм",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.moviestatus",
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="movies",
            field=models.ManyToManyField(
                blank=True,
                related_name="playlists",
                to="movies.movie",
                verbose_name="Фильмы в плейлисте",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
                verbose_name="Фильм",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="star",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="movies.ratingstar",
                verbose_name="Оценка",
            ),
        ),
        migrations.AddField(
            model_name="mainshootinggroup",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="movies.shootinggroupspecialist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritemovie",
            unique_together={("user", "movie")},
        ),
    ]
