# Generated by Django 5.0.6 on 2024-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_categorygenre_type_alter_almanach_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='music',
            field=models.BooleanField(default=False, verbose_name='Оригинальная музыка'),
        ),
    ]
