# Generated by Django 5.0.6 on 2024-09-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='movies.type', verbose_name='Вид'),
        ),
    ]
