# Generated by Django 5.0.6 on 2024-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_type_movie_kind_delete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='group_1',
            field=models.BooleanField(default=False, verbose_name='Группа 1'),
        ),
        migrations.AddField(
            model_name='genre',
            name='group_2',
            field=models.BooleanField(default=False, verbose_name='Группа 2'),
        ),
    ]
