# Generated by Django 5.0.6 on 2024-09-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_agelimit_description_alter_movie_rolled_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agelimit',
            options={'ordering': ['pk'], 'verbose_name': 'Возрастное ограничение', 'verbose_name_plural': 'Возрастные ограничения'},
        ),
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.TextField(default='Def', verbose_name='Биография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='movie',
            name='other_region',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='Другой регион'),
        ),
        migrations.AddField(
            model_name='movie',
            name='region',
            field=models.ManyToManyField(related_name='regions', to='movies.region'),
        ),
        migrations.AddField(
            model_name='producer',
            name='biography',
            field=models.TextField(default='Def', verbose_name='Биография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenarist',
            name='biography',
            field=models.TextField(default='Def', verbose_name='Биография'),
            preserve_default=False,
        ),
    ]
