# Generated by Django 5.0.6 on 2024-09-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_agelimit_options_director_biography_and_more'),
        ('regions', '0004_remove_specialist_status_remove_specialist_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AlterField(
            model_name='movie',
            name='region',
            field=models.ManyToManyField(related_name='movie_regions', to='regions.region'),
        ),
    ]
