# Generated by Django 5.0.6 on 2024-09-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_status_moviestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='region',
            new_name='regions',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rolled_certificate',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Прокатное удостоверение'),
        ),
    ]
