# Generated by Django 5.0.6 on 2024-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_rename_region_movie_regions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="almanach",
            options={
                "ordering": ["name"],
                "verbose_name": "Альманах",
                "verbose_name_plural": "Альманахи",
            },
        ),
        migrations.RemoveField(
            model_name="almanach",
            name="main",
        ),
        migrations.AddField(
            model_name="almanach",
            name="description",
            field=models.TextField(default="TEST", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="almanach",
            name="image",
            field=models.ImageField(
                default=2, upload_to="movies/main/slides", verbose_name="Картинка"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="almanach",
            name="on_slide",
            field=models.BooleanField(default=False, verbose_name="На слайде"),
        ),
        migrations.AddField(
            model_name="almanach",
            name="slide_image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="movies/main/slides",
                verbose_name="Картинка слайдера",
            ),
        ),
        migrations.AlterField(
            model_name="almanach",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Название"),
        ),
    ]
