# Generated by Django 5.0.6 on 2024-09-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0014_almanach_created_date_almanach_edit_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Almanach",
            new_name="Almanarch",
        ),
    ]
