# Generated by Django 5.0.6 on 2024-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0015_rename_almanach_almanarch"),
    ]

    operations = [
        migrations.AddField(
            model_name="almanarch",
            name="short_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Короткое название",
            ),
        ),
    ]
