# Generated by Django 5.0.6 on 2024-09-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0016_almanarch_short_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Almanarch",
            new_name="Almanac",
        ),
    ]
