# Generated by Django 5.0.6 on 2024-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_rename_almanarch_almanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almanac',
            name='slide_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='movies/main/slides', verbose_name='Картинка слайдера'),
        ),
    ]
