# Generated by Django 5.0.6 on 2024-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_almanac_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanac',
            name='laureate',
            field=models.BooleanField(default=False, verbose_name='Лауреат'),
        ),
    ]
