# Generated by Django 5.0.6 on 2024-10-01 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_almanac_laureate'),
    ]

    operations = [
        migrations.AddField(
            model_name='almanac',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год'),
        ),
    ]
