# Generated by Django 5.0.6 on 2024-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_almanac_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almanac',
            name='year',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Год'),
        ),
    ]
