# Generated by Django 5.0.6 on 2024-10-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_alter_movie_director_remove_movie_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='directors', to='movies.director', verbose_name='Режиссеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='producers', to='movies.producer', verbose_name='Продюссеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scenarist',
            field=models.ManyToManyField(blank=True, related_name='scenarists', to='movies.scenarist', verbose_name='Сценарист'),
        ),
    ]
