# Generated by Django 5.0.6 on 2024-10-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_alter_movie_director_alter_movie_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
