# Generated by Django 5.0.6 on 2024-10-05 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_alter_director_slug'),
        ('regions', '0005_compositor_director_operator_producer_scenarist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='compositor',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Композитор'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='scenarist',
        ),
        migrations.AddField(
            model_name='movie',
            name='region_compositor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.compositor', verbose_name='Композитор-регион'),
        ),
        migrations.AddField(
            model_name='movie',
            name='region_director',
            field=models.ManyToManyField(blank=True, related_name='directors', to='regions.director', verbose_name='Режиссеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='region_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.operator', verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='movie',
            name='region_producer',
            field=models.ManyToManyField(blank=True, related_name='producers', to='regions.producer', verbose_name='Продюссеры-регион'),
        ),
        migrations.AddField(
            model_name='movie',
            name='region_scenarist',
            field=models.ManyToManyField(blank=True, related_name='scenarists', to='regions.scenarist', verbose_name='Сценарист-регион'),
        ),
        migrations.DeleteModel(
            name='Compositor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Режиссеры'),
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Продюссеры'),
        ),
        migrations.DeleteModel(
            name='Scenarist',
        ),
        migrations.AddField(
            model_name='movie',
            name='scenarist',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Сценарист'),
        ),
    ]
