# Generated by Django 5.0.6 on 2024-10-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_movie_compositor_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='operator',
            field=models.CharField(max_length=2000, null=True, verbose_name='Оператор'),
        ),
    ]
