# Generated by Django 5.0.6 on 2024-10-05 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_movie_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShootingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения')),
                ('biography', models.TextField(blank=True, default=None, null=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Съемочные группы',
                'verbose_name_plural': 'Съемочная группа',
            },
        ),
        migrations.CreateModel(
            name='ShootingGroupSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименование специальности')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Специалист съемочной группы',
                'verbose_name_plural': 'Специалист съемочной группы',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='shooting_group',
            field=models.ManyToManyField(blank=True, to='movies.mainshootinggroup', verbose_name='Съемочная группа'),
        ),
        migrations.AddField(
            model_name='mainshootinggroup',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.shootinggroupspecialist'),
        ),
    ]
