# Generated by Django 5.0.6 on 2024-10-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_remove_movie_region_compositor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='shooting_group',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.mainshootinggroup', verbose_name='Съемочная группа'),
        ),
    ]
