# Generated by Django 5.0.6 on 2024-10-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_alter_movie_shooting_group'),
        ('regions', '0006_alter_director_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='compositor',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='directors', to='regions.director', verbose_name='Режиссеры-регион'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='operator',
        ),
        migrations.AddField(
            model_name='movie',
            name='compositor',
            field=models.ManyToManyField(blank=True, null=True, to='regions.compositor', verbose_name='Композитор-регион'),
        ),
        migrations.AddField(
            model_name='movie',
            name='operator',
            field=models.ManyToManyField(blank=True, null=True, to='regions.operator', verbose_name='Оператор-регион'),
        ),
    ]
