# Generated by Django 5.0.6 on 2024-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0032_remove_movie_compositor_alter_movie_director_and_more"),
        ("regions", "0007_artisticaldirector_costumerdesigner"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="artistical_director",
            field=models.ManyToManyField(
                blank=True,
                to="regions.artisticaldirector",
                verbose_name="Художник постановщик",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="costumer_designer",
            field=models.ManyToManyField(
                blank=True,
                to="regions.costumerdesigner",
                verbose_name="Художник по костюмам",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="compositor",
            field=models.ManyToManyField(
                blank=True, to="regions.compositor", verbose_name="Композитор-регион"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="operator",
            field=models.ManyToManyField(
                blank=True, to="regions.operator", verbose_name="Оператор-регион"
            ),
        ),
    ]
