# Generated by Django 5.0.6 on 2024-10-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0034_alter_rating_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="timing",
            field=models.TimeField(max_length=20, verbose_name="Хронометраж"),
        ),
    ]
