# Generated by Django 5.0.6 on 2024-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0035_alter_movie_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="timing",
            field=models.CharField(max_length=20, verbose_name="Хронометраж"),
        ),
    ]
