# Generated by Django 5.0.6 on 2024-10-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0036_alter_movie_timing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratingstar",
            options={
                "ordering": ["value"],
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
            },
        ),
        migrations.RemoveField(
            model_name="movie",
            name="voting",
        ),
        migrations.AddField(
            model_name="movie",
            name="vk_iframe",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Ссылка на iframe"
            ),
        ),
    ]
