# Generated by Django 5.0.6 on 2024-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0037_alter_ratingstar_options_remove_movie_voting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="trailer",
            field=models.TextField(
                blank=True, default=None, null=True, verbose_name="Ссылка на iframe"
            ),
        ),
    ]
