# Generated by Django 5.0.6 on 2024-10-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0038_alter_movie_trailer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="trailer",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Ссылка на iframe - трейлер",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vk_iframe",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Ссылка на iframe - фильм",
            ),
        ),
        migrations.CreateModel(
            name="FavoriteMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата добавления"),
                ),
                (
                    "edit_date",
                    models.DateField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="movies.movie",
                        verbose_name="Фильм",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_movies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
                "ordering": ["-added_date"],
                "unique_together": {("user", "movie")},
            },
        ),
    ]
