# Generated by Django 5.0.6 on 2024-10-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0041_alter_playlist_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="search_name",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Название для поиска"
            ),
        ),
    ]
